modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/issues"
[[mods]]
modId="hmag"
version="${file.jarVersion}"
displayName="Hostile Mobs and Girls"
updateJSONURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/raw/1.20.1/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls"
#logoFile="logo.png"
credits="Mechalopa"
authors="Mechalopa"
description='''More Hostile Mobs and Girls!!!'''
[[dependencies.hmag]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hmag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[modproperties.hmag]
    catalogueItemIcon="hmag:evil_crystal"