modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/issues"
[[mods]]
modId="hmag"
version="${file.jarVersion}"
displayName="Hostile Mobs and Girls"
updateJSONURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/raw/1.19.2/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls"
#logoFile="logo.png"
credits="Mechalopa"
authors="Mechalopa"
description='''More Hostile Mobs and Girls!!!'''
itemIcon="hmag:evil_crystal"
[[dependencies.hmag]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hmag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"